import React, { useState, useEffect } from 'react';
import { Card, FormField, Loader } from '../components'

const Home = () => {

  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  return (
    <section className='max-w-7xl mx-auto'>
      {/* Heading and Subtitle */}
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w[500px]'>
          Check out these awesome collections of surreal and visually stunning images generated by DALL-E OpenAI
        </p>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
          </>
        )}
      </div>
    </section>
  )
}

export default Home